name: graduation_project_2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^3.1.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  modal_progress_hud: ^0.1.3
  syncfusion_flutter_datepicker: ^18.4.33-beta
  email_validator: '^1.0.5'
  password_strength: ^0.1.3
  platform: ^2.2.1
  intl: ^0.16.1
  page_view_indicators: 1.3.1
  shared_preferences: 0.5.6
  progress_dialog: ^1.2.4
  flutter_facebook_login: 3.0.0
  http: 0.12.2
  image_picker: ^0.6.7+21
  cached_network_image: ^2.5.0
  time_picker_widget: ^1.0.0+9
  custom_radio: ^0.1.2
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf